# Generated by Django 5.0.6 on 2024-05-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='lien_bien',
            field=models.URLField(blank=True, null=True),
        ),
    ]
