# Generated by Django 5.0.4 on 2024-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rdv_lien_bien'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_bien', models.CharField(max_length=255)),
                ('surface', models.FloatField()),
                ('nombre_de_chambres', models.IntegerField()),
                ('nombre_de_toilettes', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
